openapi: 3.0.0
info:
  title: Dish-Ingredient Management API
  version: 1.0.0
  description: API for managing ingredients

servers:
  - url: http://localhost:8080

paths:

    '/ingredients':
      get:
        summary: Get all ingredients
        responses:
          '200':
            description: A list of ingredients
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Ingredient'

    '/ingredients/{id}':
      get:
        summary: Get an ingredient by ID
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: true
        responses:
          '200':
            description: Ingredient found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Ingredient'
          '404':
            description: Ingredient not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Ingredient not found

    '/ingredients/{id}/stock':
      get:
        summary: Get ingredient stock at a given time and unit
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: true
          - in: query
            name: at
            schema:
              type: string
            required: true
          - in: query
            name: unit
            required: true
            schema:
              type: string
        responses:
          "200":
            description: Stock information
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/StockValue"
          "400":
            description: Missing query parameters
            content:
              application/json:
                schema:
                  type: string
                example: "Either mandatory query parameter `at` or `unit` is not provided."
          "404":
            description: Ingredient not found
            content:
              application/json:
                schema:
                  type: string
                example: "Ingredient.id=1 is not found"

    '/dishes':
      get:
        summary: Get All Dishes
        responses:
          '200':
            description: List of dishes
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Dish"

    '/dishes/{id}/ingredients':
      put:
        summary: Update a dish
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ingredient"
        responses:
          '200':
            description: Dish Updated
            content:
              application/json:
                schema:
                  type: string
                  example: "updated"
          "400":
            description: Missing request body
            content:
              application/json:
                schema:
                  type: string
                example: "Request body is required."
          "404":
            description: Dish not found
            content:
              application/json:
                schema:
                  type: string
                example: "Dish is not found"
components:    
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: tomato
        category:
          type: string
          enum: [vegetable, animal, marine, dairy, other]
        price:
          type: number
          example: 200.00
    Dish:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Salade fraîche
        category:
          type: string
          enum: [START, MAIN, DESSERT]
        price:
          type: number
          example: 1200.00
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/Ingredient"
    StockValue:
      type: object
      properties:
        value:
          type: number
          example: 200.00
        unit:
          type: string
          enum: [PCS, KG, L]